---
title: "SolA barplot"
author: "Lieke Vlaar"
date: "20/10/2021"
output: html_document
---

# Necessary libraries

```{r libraries, show = FALSE, message = FALSE}
library(ggplot2)
library(tidyr)
library(dplyr)
library(tibble)
library(mdatools)
library(DESeq2)
library(vsn)
library(ggfortify)
library(RColorBrewer)
library(corrplot)
```

# Figure 1

```{r figure1}
sol <- read.csv("input/solA_conc_all.csv", header = TRUE, 
                  fileEncoding = "UTF-8-BOM")

sol2 <- sol %>% group_by(Sample, Company, selected) %>% summarize(meanconc =  mean(SolA_concentration_pmol.per.g.FW),
              stdevconc = sd(SolA_concentration_pmol.per.g.FW))

f1 <- ggplot(data = sol2, aes(x = reorder(Sample, desc(meanconc)), y = meanconc, fill = selected)) +
  geom_bar(stat = "identity") +
  geom_errorbar(mapping=aes(x=Sample, ymin=meanconc - stdevconc, ymax=meanconc + stdevconc), width=0.5, size=0.5) +
  geom_point(data = sol, aes(x = Sample, y = SolA_concentration_pmol.per.g.FW)) +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.title.x = element_blank()) +
  ylab("solA conc. pmol/g FW") +
  scale_fill_brewer(palette="Dark2")
f1
```


# Figure 2

First we need to import,  trim and filter the data
```{r importfiltertrim}
#import
exudate_pos <- read.csv("input/root_exudate_posM1.csv", header = TRUE, fileEncoding = "UTF-8-BOM")
exudate_neg <- read.csv("input/root_exudate_negM1.csv", header = TRUE, fileEncoding = "UTF-8-BOM")

#remove QC samples: are not important in dataset <500 samples
exudate_pos <- exudate_pos[,1:113]
exudate_neg <- exudate_neg[,1:113]

#get xp_design file
xp_design <- read.csv("input/23gt_rootweightsolA.csv", header = TRUE, fileEncoding = "UTF-8-BOM")
compounds_exudate_neg <- exudate_neg[,1:8]
compounds_exudate_pos <- exudate_pos[,1:8]
exudate_pos <- exudate_pos[,9:113]
exudate_neg <- exudate_neg[,9:113]

#filter out compounds that have a lower peak than 1.5x the average of empty pot samples
ep_p <- exudate_pos[,101:105]
ep_n <- exudate_neg[,101:105]
ep_p$mean <- rowMeans(ep_p)
ep_n$mean <- rowMeans(ep_n)
ep_p$mean1.5 <- ep_p$mean * 1.5
ep_n$mean1.5 <- ep_n$mean * 1.5
ep_pv <- as.vector(ep_p$mean1.5)
ep_nv <- as.vector(ep_n$mean1.5)
ep_pv[ep_pv<300] <- 0
ep_nv[ep_nv<300] <- 0
#this leads to too many compounds being removed. Biologically, it actually makes sense that also the empty pot contains microbes that produce important compounds. Hence, only filter out low count compounds and compounds that only have a peak in one of the 5 replicates of a genotype
filter <- function(x, xp = xp_design) {
  x <- x[rowSums(x[-1]<=1000)!=ncol(x[-1]),]
  x <- t(apply(x,1,function(r) r*rep(aggregate(r,list(xp$Genotype.name),function(x) as.numeric(median(x)>0))[,-2],
    times=c(table(xp$Genotype.name)))))
}

exu_p_f <- filter(x = exudate_pos)
exu_n_f <- filter(x = exudate_neg)
sum(exu_n_f == exudate_neg) 
```

Then we can correct for root weight, scale and centre
```{r Figure2}
#normalize for root weight
exudate_neg_t <- t(exudate_neg)
rootw <- as.vector(xp_design$root.fresh.weight..g.)
exu_n_rw <- t(t(exudate_neg_t)) / rootw

#scale and centre
exu_n_cs <- prep.autoscale(exu_n_rw, center = TRUE, scale = TRUE)
exu_n_c <- prep.autoscale(exu_n_rw, center = TRUE, scale = F)
exu_n_s <- prep.autoscale(exu_n_rw, center = F, scale = T)
boxplot(exudate_neg, main = "raw")
boxplot(exu_n_c, main = "only centered")
boxplot(exu_n_s, main = "only scaled")
boxplot(exu_n_cs, main = "centered and scaled")

exu_n_csv <- justvsn(exu_n_cs)
exu_n_sv <- justvsn(exu_n_s)
meanSdPlot(exu_n_csv)
meanSdPlot(exu_n_sv)

#check heteroscedasticity
exu_n_cs <- as.data.frame(exu_n_cs)
exu_n_cs$mean <- rowMeans(as.matrix(exu_n_cs))
exu_n_cs$sds <- rowSds(as.matrix(exu_n_cs))
ggplot(data = exu_n_cs, aes(x = mean, y = sds)) +
  geom_point()
exu_n_cs <- as.matrix(exu_n_cs)
exu_n_csv2 <- as.data.frame(exu_n_csv)
exu_n_csv2$mean <- rowMeans(exu_n_csv2)
exu_n_csv2$sds <- rowSds(as.matrix(exu_n_csv2))
ggplot(data = exu_n_csv2, aes(x = mean, y = sds)) +
  geom_point()

#colours
c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)


#remove X in names
exu_n_csv <- as.data.frame(exu_n_csv) %>% rownames_to_column("ID") 
exu_n_csv$ID <- gsub("X","",exu_n_csv$ID)
exu_n_csv <- exu_n_csv %>% column_to_rownames("ID")

#plot pca
pca_res <- prcomp(exu_n_csv, scale. = F)
exu_n_csv2 <- as.data.frame(cbind(exu_n_csv, xp_design$Genotype.name))
names(exu_n_csv2)[length(names(exu_n_csv2))]  <- "Genotype.name"
exu_n_csv2$Genotype.name <- as.factor(exu_n_csv2$Genotype.name)
autoplot(pca_res, data = exu_n_csv2, colour = 'Genotype.name', label = TRUE, shape = F, label.size = 3) + theme_minimal() + scale_color_manual(values = c25)
```


Correlation plot (Figure 2)

```{r corrplot, fig.height = 8, fig.width = 8}
corexun <- cor(exu_n_csv)
row.names(compounds_exudate_neg)[compounds_exudate_neg$Name == "SolanoeclepinA"]
corexun <- as.data.frame(corexun)
corexun <- corexun[order(-corexun$V14),]
corexun1 <- corexun[c(1:10, 2152:2161),]
corexun2 <- corexun[c(1:20),]
rn1 <- row.names(corexun1)
rn2 <- row.names(corexun2)
corexun1 <- corexun1[, which(names(corexun1) %in% rn1)] %>% as.matrix()
corexun2 <- corexun2[, which(names(corexun2) %in% rn2)] %>% as.matrix()
#order the matrices
corexun1 <- corexun1[,order(row.names(corexun1))]
rn1 <- colnames(corexun1)
corexun1 <- corexun1[match(rn1, row.names(corexun1)),]



corexun2 <- corexun2[,order(colnames(corexun2))]
rn2 <- colnames(corexun2)
corexun2 <- corexun2[match(rn2, row.names(corexun2)),]

#draw cor plot, add p value (if >0.05, add x)

testRes = cor.mtest(corexun1, conf.level = 0.95)
corrplot(corexun1, 
         order = "hclust", 
         diag = F,
         addrect = 2, 
         method = "circle",
         number.cex = 0.8,
         cl.pos = 'b', 
         p.mat = testRes$p, 
         sig.level = c(0.001, 0.01, 0.05),
         insig = "label_sig",
         pch.cex = 1,
         col = brewer.pal(n = 10, name = 'RdYlGn'))

#change names to compoundnames
rn1 <- as.data.frame(rn1)
rn1 <- gsub("V","",rn1$rn1) %>% as.data.frame()
names(rn1) <- "rn1"
compounds_exudate_neg <- compounds_exudate_neg %>% rownames_to_column("rn1")
c1 <- left_join(rn1, compounds_exudate_neg[,c("rn1","Name")], by = "rn1")
while(length(ind <- which(c1$Name == "")) > 0){
  c1$Name[ind] <- paste0("unknown_",c1$rn1[ind])
}
row.names(corexun1) <- c1$Name
corexun1 <- t(corexun1)
row.names(corexun1) <- c1$Name

#plot again
testRes = cor.mtest(corexun1, conf.level = 0.95)
corrplot(corexun1, 
         order = "hclust", 
         diag = F,
         addrect = 2, 
         method = "circle",
         type = "lower",
         number.cex = 0.8,
         cl.pos = 'b', 
         p.mat = testRes$p, 
         sig.level = c(0.001, 0.01, 0.05),
         insig = "label_sig",
         pch.cex = 1,
         tl.srt = 45,
         tl.col = "black",
         tl.cex = 0.8,
         col = brewer.pal(n = 10, name = 'RdYlGn'))
```

Correlation of hatching with unknown metabolites

```{r corr_hatching_vs_metabolites, fig.height = 8, fig.width = 8}
#metabolite matrix should not be normalized with root weight for hatching
exudate_neg_t <- as.data.frame(exudate_neg_t)
exudate_neg_t$H01 <- xp_design$Hatching
cor_h_exun <- cor(exudate_neg_t) %>% as.data.frame()
cor_h_exun <- cor_h_exun[order(-cor_h_exun$H01),]
cor_h_exun <- cor_h_exun[c(1:11, 2153:2162),]
rn <- row.names(cor_h_exun)
cor_h_exun <- cor_h_exun[, which(names(cor_h_exun) %in% rn)] %>% as.matrix()

# order the matrix
cor_h_exun <- cor_h_exun[,order(row.names(cor_h_exun))]
rn <- colnames(cor_h_exun)
cor_h_exun <- cor_h_exun[match(rn, row.names(cor_h_exun)),]

#change names to correct names
rn <- as.data.frame(rn)
rn <- gsub("V","",rn$rn) %>% as.data.frame()
names(rn) <- "rn"
compounds_exudate_neg <- compounds_exudate_neg %>% rownames_to_column("rn")
c2 <- left_join(rn, compounds_exudate_neg[,c("rn","Name")], by = "rn")
while(length(ind <- which(c2$Name == "")) > 0){
  c2$Name[ind] <- paste0("unknown_",c2$rn[ind])
}
c2[17,2] <- "hatching"
row.names(cor_h_exun) <- c2$Name
names(cor_h_exun) <- c2$Name

#draw plot
testRes = cor.mtest(cor_h_exun, conf.level = 0.95)
corrplot(cor_h_exun, 
         order = "hclust", 
         diag = F,
         addrect = 2, 
         method = "circle",
         type = "lower",
         number.cex = 0.8,
         cl.pos = 'b', 
         p.mat = testRes$p, 
         sig.level = c(0.001, 0.01, 0.05),
         insig = "label_sig",
         pch.cex = 1,
         tl.srt = 45,
         tl.col = "black",
         tl.cex = 0.8,
         col = brewer.pal(n = 10, name = 'RdYlGn'))
```




